### ISSUE TITLE
Issue installing due do windows defender bot detection

### ISSUE THREAD

**Issue by alessiovacondio** [dg5lp/FT8-Helper-2.4#3]
Deal all,

it's impossible to install due to  the issue : PUA:Win32/Puamson.A!ml This app is potentially dangerous do not install !

Any suggestiopn, hints ?

Alex

Vers. 2.2.4a

**Comment by dg5lp** [comment]
It is a false alarm.  The FT8-Helper use macro commands.  Unfortunately, most virus scanner cannot make the difference between harmful and harmless macros and indicate (false alarms).
I uploaded the exe-file to „virustotal.com“. It checks the  uploaded software with 72 different virus-scanner.  22 of 72 indicated alarm.  The exe  file was generated by the commercial program„QuickMacros“. I informed the support and received the explanation as descirbed above. It runs already on many computers, no „real“ viruses were found.  I would suggest to trust the software,

**Comment by petrkr** [comment]
> It is a false alarm. The FT8-Helper use macro commands. Unfortunately, most virus scanner cannot make the difference between harmful and harmless macros and indicate (false alarms). I uploaded the exe-file to „virustotal.com“. It checks the uploaded software with 72 different virus-scanner. 22 of 72 indicated alarm. The exe file was generated by the commercial program„QuickMacros“. I informed the support and received the explanation as descirbed above. It runs already on many computers, no „real“ viruses were found. I would suggest to trust the software,

How we can trust "it is false alarm" if  you do not released source codes ? Maybe it is just trick to let peoples override theirs firewalls/antivirus software and then you can control their PC thru some backdoor.

**Comment by dg5lp** [comment]
Hi,

 

I understand your concern. You can check the exe with “virustotal.com”.  if you do not trust 50 different virus-scanners, delivering different virus alarms, do not use the Helper. There are other FT8 automatic solutions. You can also start and test it in a virtual machine.

 

73,

DG5LP

 

Von: Petr Kracík ***@***.*** 
Gesendet: Sonntag, 16. Juni 2024 19:31
An: dg5lp/FT8-Helper-2.5
Cc: dg5lp; State change
Betreff: Re: [dg5lp/FT8-Helper-2.5] Issue installing due do windows defender bot detection (Issue #3)

 

It is a false alarm. The FT8-Helper use macro commands. Unfortunately, most virus scanner cannot make the difference between harmful and harmless macros and indicate (false alarms). I uploaded the exe-file to „virustotal.com“. It checks the uploaded software with 72 different virus-scanner. 22 of 72 indicated alarm. The exe file was generated by the commercial program„QuickMacros“. I informed the support and received the explanation as descirbed above. It runs already on many computers, no „real“ viruses were found. I would suggest to trust the software,

How we can trust "it is false alarm" if you do not released source codes ? Maybe it is just trick to let peoples override theirs firewalls/antivirus software and then you can control their PC thru some backdoor.

**Comment by petrkr** [comment]
As IT developer and devops O already know how those worms works.

For example back to 90's onehalf took few months before infection was visible, it encrypted half part of hard drive and then reflashes BIOS with 'hey here is one half'.

Even now in 21st century lotnof Ransomware will first upload all your data, then encrypt and after few weeks/months will block computer with 'pay or delete' message.

So testing in virtual environment will not proofs anything.

Also back to school we also used viruses, which was not detected by school's Avast antivirus even AVG found them, so yes I do not trust even 50 of them, if even one found malware/bad code, it means others does not have data yet.

And because you do not have it open source, nobody can check it...
So from point of IT security I'll not recommend to use it nd for example many companies will denied IT. 

We had problem with even stupid not certified CP210x UART drivers, which was not found as virus, but only was not signed those days.

I'll recommend to sign exe or publish sources for audit. But I know lot of regular peoples does not care and are able to click on every 'yes continue even certificate does nott match', but then I have to tell those peoples 'yes you lost data'. Btw you can check ransomware group 'play' how many leaked data they already have from such users.

And those users trust them, because someone else /like you/ told them 'just turn off firewall, it's false positive'.  So please  DO NOT teach peoples to do that and rather fix exe files to not be as that. If you believe it's really has No backdoor, contact those antivirus companies and ask them for delisting.

**Comment by dg5lp** [comment]
I am retired professional software developer and I am aware of the risk of viruses.

 

This project is a spare time (hobby) project without commercial interests.

I do not have big team for support of the software. This is the reason I did not published the source code.

Even if I would publish, who would audit it? And would be this person/group more trustworthy then me?

I am licensed amateur radio operator and lot of hams know me as writer of the well-known SSTV program 

GSH-PC/SAWSCAN. 

 

Another Issue would be the forking of the software. Problems with changed versions would be reported to me.

Example:  somebody changed WSJTX without changing the name/version of the forked software. It was

Reported, that the Helper does not work with WSJT-X. I required days to find out the reason…

 

I am not happy about the solution with macros, but WSJT-X does not support remote control to avoid full

automatic operation. Up to now I did not find a better solution providing all functions I required.

 

By the way, If you write a small program with QuickMacros, you will see that you will get the same virus 

warnings. From the number of feedbacks I know, that lot of folks are using the software. So far, no suspected

cases have been  reported.

 

73

 

 

Von: Petr Kracík ***@***.*** 
Gesendet: Montag, 17. Juni 2024 01:31
An: dg5lp/FT8-Helper-2.5
Cc: dg5lp; State change
Betreff: Re: [dg5lp/FT8-Helper-2.5] Issue installing due do windows defender bot detection (Issue #3)

 

As IT developer and devops O already know how those worms works.

For example back to 90's onehalf took few months before infection was visible, it encrypted half part of hard drive and then reflashes BIOS with 'hey here is one half'.

Even now in 21st century lotnof Ransomware will first upload all your data, then encrypt and after few weeks/months will block computer with 'pay or delete' message.

So testing in virtual environment will not proofs anything.

Also back to school we also used viruses, which was not detected by school's Avast antivirus even AVG found them, so yes I do not trust even 50 of them, if even one found malware/bad code, it means others does not have data yet.

And because you do not have it open source, nobody can check it...
So from point of IT security I'll not recommend to use it nd for example many companies will denied IT.

We had problem with even stupid not certified CP210x UART drivers, which was not found as virus, but only was not signed those days.

I'll recommend to sign exe or publish sources for audit. But I know lot of regular peoples does not care and are able to click on every 'yes continue even certificate does nott match', but then I have to tell those peoples 'yes you lost data'. Btw you can check ransomware group 'play' how many leaked data they already have from such users.

And those users trust them, because someone else /like you/ told them 'just turn off firewall, it's false positive'. So please DO NOT teach peoples to do that and rather fix exe files to not be as that. If you believe it's really has No backdoor, contact those antivirus companies and ask them for delisting.
